/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_FinalProj_JniDriver */

#ifndef _Included_com_example_FinalProj_JniDriver
#define _Included_com_example_FinalProj_JniDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_FinalProj_JniDriver
 * Method:    initializeDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_FinalProj_JniDriver_initializeDriver
  (JNIEnv *, jobject);

/*
 * Class:     com_example_FinalProj_JniDriver
 * Method:    printLCD
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_FinalProj_JniDriver_printLCD
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_FinalProj_JniDriver
 * Method:    printDOT
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_FinalProj_JniDriver_printDOT
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_FinalProj_JniDriver
 * Method:    printFND
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_FinalProj_JniDriver_printFND
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_FinalProj_JniDriver
 * Method:    printLED
 * Signature: (Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_com_example_FinalProj_JniDriver_printLED
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_FinalProj_JniDriver
 * Method:    runMotor
 * Signature: (Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_com_example_FinalProj_JniDriver_runMotor
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_example_FinalProj_JniDriver
 * Method:    releaseDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_FinalProj_JniDriver_releaseDriver
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
